version: "3.9"

services:
  postgres:
    container_name: to-do-list
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker2
      - POSTGRES_DB=to-do-list
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
